name: CI

on: push

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run a one-line script
        run: echo "hello install!"

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run a one-line script
        run: echo "hello test!"

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run a one-line script
        run: echo "hello build cicd!"
